[book]
title = "Notes"
authors = ["Shunya Sasaki"]
language = "en"

[build]
build-dir = ".book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "../.assets/theme"
additional-js = [
    "assets/js/mermaid.min.js",
    "assets/js/mermaid-init.js",
    "assets/js/iconify-icon.min.js",
    "assets/js/mermaid-register-icon-packs.js"
    ]
additional-css = ["assets/css/custom.css"]
